# Generated by Django 3.2 on 2021-05-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=100)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
