# Generated by Django 3.2 on 2021-04-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_101', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
