# Generated by Django 3.2 on 2021-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_102', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty_level',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
