# Generated by Django 3.2 on 2021-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_102', '0006_alter_game_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=6),
        ),
    ]
